const worksVue = [
  {
    title: 'Drone Management',
    accomplishment: ['Built with Vue 3', 'Display with Leaflet map', 'Label images with Canvas', 'Using TailwindCss', 'Use Pinia to store data'],
    img: 'Vue-Drone-desktop.png',
    mobileImg: null,
    link: null,
    website: null,
    github: null,
    tags: ['Vue3', 'Axios', 'Leaflet', 'Canvas', 'TailwindCss', 'Pinia'],
    rwd: false,
    content: '使用Vue3架構，整合無人機之案場、任務、飛行軌跡與太陽能板分析之管理系統。',
    isLong: false,
    isFlip: false,
  },
  {
    title: 'Government Portal',
    accomplishment: ['Built with Vite Vue 3', 'Write with TypeScript', 'Using ElementPlus', 'Use Pinia to store data'],
    img: 'Vue-NTPC-desktop.png',
    mobileImg: null,
    link: null,
    website: null,
    github: null,
    tags: ['Vue3', 'Vite', 'TypeScript', 'ElementPlus', 'Pinia'],
    rwd: true,
    content: '使用Vite Vue3架構，製作RWD政府員工入口網，提供單一登入入口、整合多系統快速導向，簡化系統使用流程與提高效率。',
    isLong: false,
    isFlip: false,
  },
  {
    title: 'App Store',
    accomplishment: ['Built with Vue 3', 'Using ElementPlus', 'Use Vuex to store data'],
    img: 'Vue-AppStore-desktop.png',
    mobileImg: null,
    link: null,
    website: null,
    github: null,
    tags: ['Vue3', 'Axios', 'ElementPlus', 'Vuex'],
    rwd: false,
    content: '使用Vue3架構，實現應用程式之管理系統。',
    isLong: false,
    isFlip: false,
  },
  {
    title: 'API Gateway',
    accomplishment: ['Built with Vite Vue 3', 'Write with TypeScript', 'Using WindiCss', 'Use Pinia to store data'],
    img: 'Vue-APIGateway-desktop.png',
    mobileImg: null,
    link: null,
    website: null,
    github: null,
    tags: ['Vue3', 'Vite', 'TypeScript', 'WindiCss', 'Pinia'],
    rwd: true,
    content: '使用Vite Vue3架構，實現API Gateway之管理系統。',
    isLong: false,
    isFlip: false,
  },
  {
    title: 'Bus App',
    accomplishment: ['Built with Vue 3', 'Call Open API', 'Display with Leaflet map'],
    img: 'Vue-BusApp-desktop.png',
    mobileImg: 'Vue-BusApp-mobile.png',
    link: 'https://weichieh123.github.io/Open-API/#/bus-line',
    website: 'https://weichieh123.github.io/Open-API/#/bus-line',
    github: 'https://github.com/weichieh123/Open-API',
    tags: ['Vue3', 'Open API', 'Axios', 'Leaflet'],
    rwd: true,
    content: '使用Vue3架構，串接Open API，實現公車路線查詢之功能。',
    isLong: false,
    isFlip: false,
  },
  {
    title: 'F.H. Museum',
    accomplishment: ['Built with Vue 3', 'Scss management', 'Responsive Web Design'],
    img: 'Vue-FransHals-desktop.png',
    mobileImg: 'Vue-FransHals-mobile.png',
    link: 'https://weichieh123.github.io/Vue-FransHalsMuseum/',
    website: 'https://weichieh123.github.io/Vue-FransHalsMuseum/',
    github: 'https://github.com/weichieh123/Vue-FransHalsMuseum',
    tags: ['Vue3', 'Layout', 'Scss', 'RWD'],
    rwd: true,
    content: '使用Vue3架構，以FransHals Museum網站為參考做切版練習。',
    isLong: true,
    isFlip: false,
  },
  {
    title: 'Covid19 App',
    accomplishment: ['Built with Vue 3', 'Call Open data', 'Display with Leaflet map'],
    img: 'Vue-Covid19TestApp-desktop.png',
    mobileImg: 'Vue-Covid19TestApp-mobile.png',
    link: 'https://weichieh123.github.io/covid19-test-app/',
    website: 'https://weichieh123.github.io/covid19-test-app/',
    github: 'https://github.com/weichieh123/covid19-test-app',
    tags: ['Vue3', 'Open Data', 'Axios', 'Leaflet'],
    rwd: true,
    content: '使用Vue3架構，串接下載衛服部之開放式資料，實現快篩試劑庫存查詢之功能。',
    isLong: true,
    isFlip: false,
  },
  {
    title: 'Todo App',
    accomplishment: ['Built with Vue 2', 'CRUD'],
    img: 'Vue-TodoApp-desktop.png',
    mobileImg: '',
    link: 'https://weichieh123.github.io/Vue-TodoApp/',
    website: 'https://weichieh123.github.io/Vue-TodoApp/',
    github: 'https://github.com/weichieh123/Vue-TodoApp',
    tags: ['Vue2'],
    rwd: false,
    content: '使用Vue2架構，實現新增、修改、刪除、查詢之功能。',
    isFlip: false,
  },
];

export default worksVue;
